import React from 'react'
import About from './About'
import { Metadata } from 'next';
export const metadata: Metadata = {
    title: "About Us",
    description: "Generated by create next app",
};
const page = () => {
    return (
        <div>
            <About />
        </div>
    )
}

export default page
