import React from 'react'
import Faqs from './Faqs'
import { Metadata } from 'next';
export const metadata: Metadata = {
    title: "Faqs",
    description: "Generated by create next app",
};
const page = () => {
    return (
        <div>
            <Faqs />
        </div>
    )
}

export default page
