import React from 'react'
import Deals from './Deals'
import { Metadata } from 'next';


export const metadata: Metadata = {
  title: "Deals",
  description: "Generated by create next app",
};

function page() {
  return (
    <div>
      <Deals/>
    </div>
  )
}

export default page
