import React from 'react'
import FeelingToday from './FeelingToday'
import { Metadata } from 'next';
export const metadata: Metadata = {
    title: "Feeling-Today",
    description: "Generated by create next app",
};

const page = () => {
    return (
        <div className='min-h-'>
            <FeelingToday />
        </div>
    )
}

export default page
