import React from 'react'
import Treats from './Treats'
import { Metadata } from 'next';
export const metadata: Metadata = {
    title: "Special Treats",
    description: "Generated by create next app",
};
const page = () => {
    return (
        <div>
            <Treats />
        </div>
    )
}

export default page
