import React from 'react'
import AddDeals from './AddDeals'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Add Deals",
  description: "Generated by create next app",
};
function page() {
  return (
    <div>
      <AddDeals/>
    </div>
  )
}

export default page
