import React from 'react'
import Support from './Support'
import { Metadata } from 'next';
export const metadata: Metadata = {
    title: "Support",
    description: "Generated by create next app",
};

const page = () => {
    return (
        <div>
            <Support />
        </div>
    )
}

export default page
