import React from 'react'
import Help from './Help'
import { Metadata } from 'next';
export const metadata: Metadata = {
    title: "Discussion Board",
    description: "Generated by create next app",
};
const page = () => {
    return (
        <div>
            <Help />
        </div>
    )
}

export default page
