import React from 'react'
import PrivacyAndPolicy from './PrivacyAndPolicy'
import { Metadata } from 'next';
export const metadata: Metadata = {
    title: "Privacy & Policy",
    description: "Generated by create next app",
};
const page = () => {
    return (
        <div>
            <PrivacyAndPolicy />
        </div>
    )
}

export default page
