
import { Metadata } from 'next';
import EditBanner from './EditBanner'



export const metadata: Metadata = {
  title: "Edit Banner",
  description: "Generated by create next app",
};

function page() {
  return (
    <>
    <EditBanner/>
    </>
  )
}

export default page
