import React from 'react'
import FaceChallenges from './FaceChallenges'
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: "Face-Challenges",
    description: "Generated by create next app",
};

const page = () => {
    return (
        <div>
            <FaceChallenges />
        </div>
    )
}

export default page
