import React from 'react'
import EditProfile from './EditProfile'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Edit Profile",
  description: "Generated by create next app",
};
function page() {
  return (
    <>
      <EditProfile/>
    </>
  )
}

export default page
