import React from 'react'
import NewPassword from './NewPassword'
import  "../../../globals.css"
import type { Metadata } from "next";
export const metadata: Metadata = {
    title: "New Password",
    description: "Generated by create next app",
};
const page = () => {
    return (
        <div>
            <NewPassword />
        </div>
    )
}

export default page
