import React from "react";
import VerticleSlider from "../components/slider";
import { Metadata } from "next";
import useTokenRedirect from "@/app/components/reuseables/useTokenRedirect";


export const metadata: Metadata = {
  title: "Select Template",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <VerticleSlider />
    </div>
  );
};

export default page;
