import React from 'react'
import AddFriend from './AddFriend'
import { Metadata } from 'next';
export const metadata: Metadata = {
    title: "Add a Friend",
    description: "Generated by create next app",
};
const page = () => {
    return (
        <div>
            <AddFriend />
        </div>
    )
}

export default page
