import React from 'react'
import Signin from './Signin'
import "../../../globals.css"
import type { Metadata } from "next";
import { GoogleOAuthProvider } from '@react-oauth/google';
export const metadata: Metadata = {
    title: "Sign in",
    description: "Generated by create next app",
};
const page = () => {
    return (
        <div>
            <GoogleOAuthProvider clientId={`${process.env.GOOGLE_CLIENT_ID}`} >
                <Signin />
            </GoogleOAuthProvider>

        </div>
    )
}

export default page
