import React from 'react'
import Profile from './Profile'
import { Metadata } from 'next';
export const metadata: Metadata = {
    title: "Profile",
    description: "Generated by create next app",
};
const page = () => {
    return (
        <div>
            <Profile />
        </div>
    )
}

export default page
