import React from 'react'
import Notifications from './Notifications'
import { Metadata } from 'next';
export const metadata: Metadata = {
    title: "Notifications",
    description: "Generated by create next app",
};
const page = () => {
    return (
        <div>
            <Notifications />
        </div>
    )
}

export default page
