import React from 'react'
import Settings from './Settings'
import { Metadata } from 'next';
export const metadata: Metadata = {
    title: "Settings",
    description: "Generated by create next app",
};

const page = () => {
    return (
        <div>
            <Settings />
        </div>
    )
}

export default page
