import React from 'react'
import PasswordSuccess from './PasswordSuccess'
import  "../../../globals.css"
import type { Metadata } from "next";
export const metadata: Metadata = {
    title: "Password Success",
    description: "Generated by create next app",
};
const page = () => {
    return (
        <div>
            <PasswordSuccess />
        </div>
    )
}

export default page
