import React from 'react'
import { Metadata } from 'next';
// import EditDealsWrapper from './EditDeals';
import dynamic from 'next/dynamic'

const EditDealsWrapper = dynamic(() => import('./EditDeals'), {
  ssr: false,
})

export const metadata: Metadata = {
  title: "Edit Deals",
  description: "Generated by create next app",
};


const Page = () => {
  return (
    <React.Fragment>
      <EditDealsWrapper />
    </React.Fragment>
  )
}

export default Page 