import React from "react";
import "../../../globals.css";
import type { Metadata } from "next";
import SocialLogin from "./SocialLogin";

export const metadata: Metadata = {
  title: "Sign up",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div>
      <SocialLogin />
    </div>
  );
};

export default page;
