import type { Metadata } from "next";
import { Inter, Montserrat, Roboto, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import store from "./redux/store";
import { ReduxProvider } from "./redux/ReduxProvider";


const montserrat = Montserrat({
  subsets: ["latin"],
  variable: '--font-montserrat',

});

const inter = Inter({
  subsets: ["latin"],
  variable: '--font-inter',

});

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
  weight: "400"
})



export const metadata: Metadata = {
  title: "AtypicallyMe",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico'
  }
}

{console.log('workingLAYOUT')}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body className={`${montserrat.variable} ${roboto.variable} ${inter.variable}`}>
          {children}
        </body>
      </ReduxProvider>
    </html>
  );
}
