import { Metadata } from "next";
import Options from "./Options"
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Outing Option Details",
  description: "Generated by create next app",
};
function page() {
  return (
    <>
      <Suspense fallback={<div>Loading...</div>}>
        <Options />
      </Suspense>
    </>
  )
}

export default page