import React, { Suspense } from 'react'
import AskQuestion from './AskQuestion'
import '../../../../globals.css'
import { Metadata } from 'next';
export const metadata: Metadata = {
    title: "Ask a question",
    description: "Generated by create next app",
};
const page = () => {
    return (
        <div>
            <Suspense fallback={<div>Loading...</div>}>
                <AskQuestion />
            </Suspense>
        </div>
    )
}

export default page