import React from 'react'
import ResetPassword from './ResetPassword'
import  "../../../globals.css"
import type { Metadata } from "next";
export const metadata: Metadata = {
    title: "Reset Password",
    description: "Generated by create next app",
};

const page = () => {
    return (
        <div>
            <ResetPassword />
        </div>
    )
}

export default page
