import React from 'react'
import Upload from './Upload'
import  "../../../globals.css"
import type { Metadata } from "next";
export const metadata: Metadata = {
    title: "Profile",
    description: "Generated by create next app",
};
const page = () => {
    return (
        <div>
            <Upload />
        </div>
    )
}

export default page
