import React from 'react'
import Community from './Community'
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: "Community",
    description: "Generated by create next app",
};
const page = () => {
    return (
        <div>
            <Community />
        </div>
    )
}

export default page
