import React from 'react'
import "../../../globals.css"
import type { Metadata } from "next";
import Signup from './Sign-up';
import { GoogleOAuthProvider } from '@react-oauth/google';

export const metadata: Metadata = {
    title: "Sign up",
    description: "Generated by create next app",
};
const page = () => {
    return (
        <div>
            <GoogleOAuthProvider clientId={`${process.env.GOOGLE_CLIENT_ID}`} >
                <Signup />
            </GoogleOAuthProvider>
        </div>
    )
}

export default page
