import type { Metadata } from "next";
import { Inter, Montserrat, Roboto, Roboto_Mono } from "next/font/google";
import "../../../globals.css";


const montserrat = Montserrat({
    subsets: ["latin"],
    variable: '--font-montserrat',

});

const inter = Inter({
    subsets: ["latin"],
    variable: '--font-inter',

});

const roboto = Roboto({
    subsets: ['latin'],
    variable: '--font-roboto',
    weight: "400"
})



export const metadata: Metadata = {
    title: "Welcome",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${montserrat.variable} ${roboto.variable} ${inter.variable}`}>
                {children}
            </body>
        </html>
    );
}
