import React from 'react'
import Welcome from './Welcome'
import  "../../../globals.css"
import type { Metadata } from "next";
export const metadata: Metadata = {
    title: "Welcome",
    description: "Generated by create next app",
};
const page = () => {
    return (
        <div>
            <Welcome />
        </div>
    )
}

export default page
