import React from 'react'
import MakeBetterDay from './MakeBetterDay'
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: "Make Better Day",
    description: "Generated by create next app",
};

const page = () => {
    return (
        <div>
            <MakeBetterDay />
        </div>
    )
}

export default page
