import React from 'react'
import Subscription from './Subscription'
import { Metadata } from 'next';
export const metadata: Metadata = {
    title: "Subscription",
    description: "Generated by create next app",
};
const page = () => {
    return (
        <div>
            <Subscription />
        </div>
    )
}

export default page
