import React, { Suspense } from 'react'
import DiscussionBoard from './DiscussionBoard'
import { Metadata } from 'next';
export const metadata: Metadata = {
    title: "Discussion Board",
    description: "Generated by create next app",
};
const page = () => {
    return (
        <div>
            <Suspense fallback={<div>Loading...</div>}>
                <DiscussionBoard />
            </Suspense>
        </div>
    )
}

export default page