import React from 'react'
import TermsAndConditions from './TermsAndConditions'
import { Metadata } from 'next';
export const metadata: Metadata = {
    title: "Terms & Conditions",
    description: "Generated by create next app",
};

const page = () => {
    return (
        <div>
            <TermsAndConditions />
        </div>
    )
}

export default page
